name: Release

on: workflow_dispatch

jobs:

  linux-windows-build:
    name: CSharp Build
    runs-on: windows-latest
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
  
    - name: Check out code
      uses: actions/checkout@v4

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Download Tools
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
        Invoke-WebRequest -Uri https://github.com/moloch--/minisign/releases/download/v0.2.1/minisign.exe -OutFile minisign.exe

    - name: MSBuild
      run: |
        dotnet msbuild Seatbelt.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=compiled/
        ls

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Seatbelt
        path: Seatbelt\compiled\Seatbelt.exe
