name: Release

on: workflow_dispatch

jobs:

  linux-windows-build:
    name: CSharp Build
    runs-on: windows-latest
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
  
    - name: Check out code
      uses: actions/checkout@v4

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Download Tools
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
        Invoke-WebRequest -Uri https://github.com/moloch--/minisign/releases/download/v0.2.1/minisign.exe -OutFile minisign.exe

    - name: MSBuild
      run: |
        msbuild.exe Seatbelt.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=compiled/
        ls
        Copy-Item -Path Seatbelt\compiled\Seatbelt.exe -Destination compiled\Seatbelt.exe

    - name: Build Package
      run: |
        $Version = git.exe describe --tags --abbrev=0
        $Version = "`"$Version`""
        Get-Content -Path alias.json | .\jq.exe ".version |= `"$Version`"" > ./compiled/alias.json
        Copy-Item -Path LICENSE -Destination compiled\LICENSE
        cd compiled
        ls
        tar.exe -czvf ..\seatbelt.tar.gz .
      
    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          seatbelt.tar.gz
